const arrayOfMajors = [
    "Any",
    "Nursing",
    "Liberal Arts",
    "Business Administration",
    "General Studies",
    "Psychology",
    "Biology",
    "Communications",
    "Accounting",
    "Medical Assistant",
    "Social Work",
    "Cosmetology",
    "Mechanical Engineering",
    "Finance",
    "Computer Science",
    "Criminal Justice",
    "Licensed Practical Nurse (LPN)",
    "Advertising and Marketing",
    "Welding",
    "Nursing Assistant",
    "Political Science",
    "Bookkeeping",
    "English",
    "Elementary Education",
    "Auto Mechanic",
    "Law",
    "Sociology",
    "Educational Leadership and Administration",
    "Sports Management",
    "Early Childhood Education",
    "Kinesiology And Exercise Science",
    "Electrical Engineering",
    "Economics",
    "Education",
    "EMT & Paramedic",
    "History",
    "Law and Justice Administration",
    "Math",
    "Healthcare Administration",
    "Information Technology",
    "Esthetician",
    "Civil Engineering",
    "Chemistry",
    "Heating and Air Conditioning (HVAC)",
    "Special Education",
    "Public Health",
    "Medicine",
    "Social Science",
    "Counseling Psychology",
    "Curriculum and Instruction",
    "Electrician",
    "Information Science",
    "Dental Assistant",
    "Public Administration",
    "Bus and Truck Driver",
    "Human Resources",
    "Pharmacy",
    "Family Practice Nurse",
    "Chemical Engineering",
    "Sports Medicine",
    "Computer Networking",
    "Human Services",
    "International Relations",
    "Physical Therapy",
    "Journalism",
    "Organizational Leadership",
    "Physics",
    "Culinary Arts",
    "Guidance Counselor",
    "Information Systems",
    "Biomedical Engineering",
    "Massage Therapy",
    "Fine Arts and Studio Arts",
    "Music",
    "Drama and Theatre Arts",
    "Ultrasound Technician",
    "Radiology Technician",
    "Computer Aided Design (CAD)",
    "Management Science",
    "Anthropology",
    "Physician Assistant",
    "Nail Technician",
    "Paralegal",
    "Biochemistry",
    "Family Studies",
    "Engineering",
    "Diesel Mechanic",
    "Industrial Engineering",
    "Veterinary Assistant",
    "Criminology",
    "International Business",
    "Biomedical Science",
    "Occupational Therapy",
    "Secondary Education",
    "Nursing Administration",
    "Logistics and Supply Chain Management",
    "Medical Insurance Coding",
    "Medical Executive Assistant",
    "Health Information and Medical Records Technology",
    "Environmental Science",
    "Administrative Assistant",
    "Physical Education",
    "Graphic Design",
    "Pharmacy Technician",
    "Dental Hygienist",
    "Fire Science",
    "Spanish Language and Literature",
    "Phlebotomy",
    "Neuroscience",
    "Cinematography And Film",
    "Surgical Technologist",
    "Computer Programming",
    "Industrial Mechanics",
    "Audiology and Speech Pathology",
    "Multimedia",
    "Physical Therapist Assistant",
    "Medical Insurance Biller",
    "Entrepreneurship",
    "Philosophy",
    "Molecular Biology",
    "Geology",
    "International and Global Studies",
    "Audio and Video Production",
    "Ministry",
    "Respiratory Therapy",
    "Animal Science",
    "Statistics",
    "Osteopathy",
    "Software Engineering",
    "Reading Teacher and Literacy Specialist",
    "Dentistry",
    "Mental Health Counseling",
    "Creative Writing",
    "Theology",
    "Architecture",
    "Organizational and Nonprofit Management",
    "Substance Abuse and Addiction Counseling",
    "Aircraft Mechanic",
    "Web Design",
    "Interior Design",
    "Public Relations",
    "Operations Management",
    "Design and Visual Communications",
    "ESL",
    "Industrial Technology",
    "Medical Office Assistant",
    "Manufacturing Engineering Technician",
    "Athletic Training",
    "Clinical Psychology",
    "Real Estate",
    "Engineering Management",
    "Public Policy",
    "Auto Body",
    "Animation",
    "Geography",
    "Office Management and Supervision",
    "Occupational Therapy Assistant (OTA)",
    "Baking And Pastry",
    "Nutrition",
    "Nursing Science",
    "Hospital and Healthcare Facility Management",
    "Exercise Physiology",
    "Child Care",
    "Machinist",
    "Child Development",
    "Medical Lab Technician",
    "Talmudic Studies",
    "Carpentry",
    "Risk Management and Insurance",
    "Aviation",
    "Fashion Merchandising",
    "Higher Education Administration",
    "Fire Prevention",
    "Commercial and Advertising Art",
    "Medical Office Management",
    "Corrections Officer",
    "Dietetics",
    "Organizational Behavior Studies",
    "Medical Technology",
    "Construction Management",
    "Behavioral Science",
    "Forensic Psychology",
    "Parks and Recreation Management",
    "Biotechnology",
    "Forensic Science",
    "Materials Engineering",
    "Optometry",
    "Art History",
    "Systems Engineering",
    "Agriculture",
    "Religious Studies",
    "Sales Manager",
    "Project Management",
    "Fashion Design",
    "Nutrition",
    "Marriage and Family Therapy",
    "Veterinary Medicine",
    "Financial Planning",
    "Middle School Teacher",
    "School Psychology",
    "Christian Counseling",
    "Business & Finance",
    "Medicine & Allied Health",
    "Education",
    "Skilled Trades & Repair Services",
    "Communication & Media",
    "Psychology",
    "Law & Criminal Justice",
    "Administration & Social Services",
    "Liberal Arts and Humanities",
    "Nutrition and Wellness",
    "Computers & Information Technology",
    "Physical & Life Sciences",
    "Engineering & Architecture",
    "Arts & Design",
    "Social Sciences",
    "Animal & Agriculture Studies",
    "Beauty & Hospitality Services",
];
export default arrayOfMajors;
